import fs from 'fs';
import path from 'path';
import fg from 'fast-glob';
const { glob } = fg;
import logger from '../utils/logger.js';
import ASTProvider from '../ast/ASTProvider.js';
import readline from 'readline';
import { patterns } from './patterns.js';
// 661 LOC 모놀리스에서 분리된 헬퍼/구조화 스캐너 모듈
import {
  isFalsePositive,
  isTestKey,
  isCommentLine,
  collectXmlCommentRanges,
  isLowConfidenceMatch,
  extractMatchDetails,
  getEnvVarName,
  getLineNumber
} from './scannerHelpers.js';
import { scanStructuredFile } from './structuredScanner.js';

/**
 * Scans for sensitive files that should never be committed.
 */
async function scanSensitiveFiles(repoPath, platforms) {
  const warnings = [];
  const sensitiveFiles = platforms.flatMap(p => p.sensitiveFiles || []);

  for (const sf of sensitiveFiles) {
    const found = await glob(sf.glob, {
      cwd: repoPath,
      ignore: ['**/node_modules/**', '**/Pods/**', '**/.git/**'],
      absolute: true
    });

    for (const filePath of found) {
      warnings.push({
        file: path.relative(repoPath, filePath),
        line: 0,
        match: path.basename(filePath),
        fullMatch: path.basename(filePath),
        patternName: `Sensitive File: ${path.basename(filePath)}`,
        severity: sf.severity,
        isTestKey: false,
        isSensitiveFile: true,
        content: sf.reason,
        isLikelyExample: false
      });
    }
  }

  return warnings;
}

async function scanSmallFile(filePath, repoPath, allPatterns, platforms, results, usedEnvNames, options) {
  let content;
  try {
    content = fs.readFileSync(filePath, 'utf8');
  } catch (err) {
    logger.warn(`Could not read file ${filePath}: ${err.message}`);
    return;
  }
  const lines = content.split('\n');
  const ext = path.extname(filePath);
  const astLang = ASTProvider.getLangId(ext);

  if (content.length > 100000 && !content.includes('\n')) return;

  const firstTenLines = lines.slice(0, 10).join('\n').toLowerCase();
  if (firstTenLines.includes('auto-generated') || firstTenLines.includes('generated by')) return;

  // XML/HTML/Maven comment ranges span multiple lines; line-based comment
  // detection misses them. Pre-compute byte ranges for `<!-- -->` blocks
  // (XML, HTML, pom.xml, .yml) so URL/secret matches inside reference docs
  // can be skipped (#4.7).
  const xmlCommentRanges = (ext === '.xml' || ext === '.html' || ext === '.htm' || ext === '.svg' || ext === '.yml' || ext === '.yaml')
    ? collectXmlCommentRanges(content)
    : [];
  const inXmlComment = (offset) => xmlCommentRanges.some(([s, e]) => offset >= s && offset < e);

  for (const pattern of allPatterns) {
    // .matchAll() 은 lastIndex 공유 없이 fresh iterator 반환 — 동시성 안전
    // (이전: pattern.regex.exec 루프는 모듈 전역 정규식의 lastIndex 를 공유)
    for (const match of content.matchAll(pattern.regex)) {
      let { matchValue, varName } = extractMatchDetails(pattern, match, content, ext);

      if (astLang && !options.skipAST) {
        // Use offset of the captured value (not match[0]) so AST validation hits the string literal,
        // not surrounding identifiers (e.g., `apiKey` in `apiKey = "..."`).
        const valueOffsetInMatch = match[0].indexOf(matchValue);
        const valueOffset = match.index + (valueOffsetInMatch >= 0 ? valueOffsetInMatch : 0);
        const isValid = await ASTProvider.validateMatch(filePath, astLang, matchValue, valueOffset, { allowComments: options.scanComments === true });
        if (!isValid) continue;
      }

      if (inXmlComment(match.index)) continue;

      const startLine = getLineNumber(content, match.index);
      const currentLineText = lines[startLine - 1] || '';
      const isComment = isCommentLine(currentLineText, platforms);

      if (isLowConfidenceMatch(matchValue, pattern.name, varName)) continue;
      if (isComment && !options.scanComments) continue;

      const envVarName = getEnvVarName(pattern, varName, match[2], usedEnvNames, matchValue);
      const isTest = isTestKey(currentLineText, filePath, matchValue);

      results.push({
        file: path.relative(repoPath, filePath),
        line: startLine,
        match: matchValue,
        fullMatch: match[0],
        patternName: pattern.name,
        envVarName,
        severity: isTest ? 'LOW' : pattern.severity,
        isFixable: pattern.isFixable !== false,
        isTestKey: isTest,
        isSensitiveFile: false,
        isComment,
        isMultiline: pattern.multiline || match[0].includes('\n'),
        content: currentLineText.trim(),
        isLikelyExample: isFalsePositive(currentLineText, filePath)
      });
    }
  }

  scanStructuredFile(filePath, repoPath, content, results, usedEnvNames);
}

async function scanLargeFile(filePath, repoPath, allPatterns, platforms, results, usedEnvNames, options) {
  let fileStream;
  try {
    fileStream = fs.createReadStream(filePath);
  } catch (err) {
    logger.warn(`Could not create read stream for ${filePath}: ${err.message}`);
    return;
  }
  const rl = readline.createInterface({ input: fileStream, crlfDelay: Infinity });
  const ext = path.extname(filePath);
  const astLang = ASTProvider.getLangId(ext);

  let lineNumber = 0;
  let byteOffset = 0;

  for await (const line of rl) {
    lineNumber++;
    for (const pattern of allPatterns) {
      if (pattern.multiline) continue;

      // matchAll 사용 — lastIndex 공유 회피
      for (const match of line.matchAll(pattern.regex)) {
        let matchValue = match[0];
        if (pattern.name.includes('Objective-C') && match[1]) matchValue = match[2];
        else {
           for (let g = match.length - 1; g >= 1; g--) {
             if (match[g] !== undefined) { matchValue = match[g]; break; }
           }
        }

        if (astLang && !options.skipAST) {
           const valueOffsetInMatch = match[0].indexOf(matchValue);
           const valueOffset = byteOffset + match.index + (valueOffsetInMatch >= 0 ? valueOffsetInMatch : 0);
           const isValid = await ASTProvider.validateMatch(filePath, astLang, matchValue, valueOffset, { allowComments: options.scanComments === true });
           if (!isValid) continue;
        }

        if (isLowConfidenceMatch(matchValue, pattern.name)) continue;

        const lineIsComment = isCommentLine(line, platforms);
        if (lineIsComment && !options.scanComments) continue;

        const isTest = isTestKey(line, filePath, matchValue);
        const envVarName = getEnvVarName(pattern, '', '', usedEnvNames, matchValue);

        results.push({
          file: path.relative(repoPath, filePath),
          line: lineNumber,
          match: matchValue,
          fullMatch: match[0],
          patternName: pattern.name,
          envVarName,
          severity: isTest ? 'LOW' : pattern.severity,
          isFixable: pattern.isFixable !== false,
          isTestKey: isTest,
          isSensitiveFile: false,
          isComment: lineIsComment,
          isMultiline: false,
          content: line.trim(),
          isLikelyExample: isFalsePositive(line, filePath)
        });
      }
    }
    byteOffset += Buffer.byteLength(line, 'utf8') + 1;
  }
}

export async function scanProject(repoPath, platforms, options = {}) {
  const results = [];
  const extensions = new Set();
  const usedEnvNames = new Map();

  platforms.forEach(p => {
    (p.commonExtensions || []).forEach(ext => extensions.add(ext));
  });

  if (extensions.size === 0) {
    ['.swift', '.kt', '.dart', '.xml', '.plist', '.json', '.env', '.properties', '.gradle'].forEach(ext => extensions.add(ext));
  }

  const platformIgnores = platforms.flatMap(p => p.ignorePaths || []);
  const ignorePatterns = [
    '**/node_modules/**', '**/Pods/**', '**/Carthage/**', '**/vendor/**', '**/third_party/**',
    '**/build/**', '**/dist/**', '**/.git/**', '**/.env',
    // 1. 키, 인증서 및 보안 파일
    '**/id_rsa', '**/id_rsa.pub', '**/*.ppk', '**/known_hosts',
    '**/*.pem', '**/*.cer', '**/*.crt', '**/*.p12', '**/*.keystore', '**/*.jks', '**/*.certSigningRequest',
    '**/.aws/credentials', '**/gcp-sa-key.json', '**/*.ovpn', '**/*.mobileprovision',
    // 2. 메모리 덤프 및 런타임 로그
    '**/*.hprof', '**/*.dump', '**/core.*',
    '**/*.log', '**/*.crash', '**/*.out',
    '**/*.sqlite', '**/*.db', '**/*.realm',
    // 3. 인프라 배포 및 환경 설정 스크립트
    '**/*.sh', '**/*.bat', '**/*.command',
    '**/*.tfstate', '**/terraform.tfvars',
    '**/Fastfile', '**/Appfile', '**/Matchfile',
    // 4. 로컬 빌드 환경 변수
    '**/local.properties', '**/.npmrc', '**/.yarnrc',
    // 5. 모바일 빌드 산출물 / Xcode-IDE 캐시
    '**/*.dSYM/**', '**/*.ipa', '**/*.app/**', '**/*.xcarchive/**',
    '**/xcuserdata/**', '**/*.xcuserstate',
    '**/*.apk', '**/*.aab', '**/*.iml', '**/*.bks',
    '**/lint-results-*.xml', '**/lint-baseline.xml',
    // 6. Flutter 자동생성 / 데스크톱 플랫폼
    '**/.flutter-plugins', '**/.flutter-plugins-dependencies',
    '**/Generated.xcconfig', '**/flutter_export_environment.sh',
    '**/.metadata', '**/.last_build_id',
    // 7. 패키지 매니저 인증 / IDE 워크스페이스
    '**/.netrc', '**/_netrc',
    '**/.docker/config.json', '**/.dockercfg',
    '**/.kube/config', '**/*.kubeconfig', '**/.htpasswd',
    '**/auth.json', '**/.composer/auth.json',
    '**/.bundle/config', '**/.gem/credentials',
    '**/.pypirc', '**/.cargo/credentials', '**/.cargo/credentials.toml',
    '**/.idea/workspace.xml', '**/.idea/dataSources.xml', '**/.idea/dataSources/**',
    '**/.vscode/sftp.json',
    // 8. 환경변수 변형 / Rails 시크릿 / 일반 시크릿 컨벤션
    '**/.env.local', '**/.env.*.local',
    '**/.env.development', '**/.env.production', '**/.env.staging', '**/.env.test',
    '**/.env.vault',
    '**/secrets.yml', '**/secrets.yaml', '**/secrets.json', '**/*.secrets',
    '**/*.kdbx', '**/*.kdb',
    '**/master.key', '**/.master.key',
    '**/config/master.key', '**/config/credentials/*.yml.enc',
    '**/service-account*.json', '**/*-credentials.json', '**/credentials.json',
    '**/.firebaserc', '**/firebase-debug.log',
    // 9. 추가 인증/암호화 자산
    '**/*.pfx', '**/*.gpg', '**/*.asc', '**/*.enc',
    // 10. 백업 / 임시 / OS 메타
    '**/*.swp', '**/*.swo', '**/*.bak', '**/*.backup', '**/*~',
    '**/.DS_Store', '**/Thumbs.db',
    // 11. 컴파일 산출물 / 네이티브 라이브러리 / 압축
    '**/*.class', '**/*.jar', '**/*.aar', '**/*.war', '**/*.ear',
    '**/*.so', '**/*.a', '**/*.dll', '**/*.dylib', '**/*.lib',
    '**/*.pyc', '**/__pycache__/**',
    '**/*.zip', '**/*.tar', '**/*.tar.gz', '**/*.tgz', '**/*.7z', '**/*.rar',
    '**/*.dmg', '**/*.pkg',
    // 12. DB 데이터 덤프 추가
    '**/*.sql', '**/*.sql.gz', '**/dump.sql',
    '**/*.bson', '**/*.mdb', '**/*.accdb', '**/*.dbf',
    ...platformIgnores, ...(options.ignore || [])
  ];

  // .blinderSettings 추가 ignorePaths 병합
  // - silent catch 제거: 잘못된 JSON 사용자 알림 위해 logger.warn 출력
  // - 스키마 검증(타입/배열) 추가: 잘못된 설정으로 downstream 크래시 방지
  // 참고: bin/blinder.js 호출 경로는 이미 utils/config.js loadConfig 가
  // 동일 파일을 검증해 options.ignore 로 전달하므로 여기 호출은 안전망 역할.
  const rcPath = path.join(repoPath, '.blinderSettings');
  if (fs.existsSync(rcPath)) {
    try {
      const raw = fs.readFileSync(rcPath, 'utf8');
      const rcContent = JSON.parse(raw);
      if (!rcContent || typeof rcContent !== 'object' || Array.isArray(rcContent)) {
        throw new Error('루트는 JSON 객체여야 합니다');
      }
      if (rcContent.ignorePaths !== undefined) {
        if (!Array.isArray(rcContent.ignorePaths)) {
          throw new Error('"ignorePaths" 는 배열이어야 합니다');
        }
        ignorePatterns.push(...rcContent.ignorePaths);
      }
    } catch (err) {
      logger.warn(`.blinderSettings 파싱 실패 (${err.message}). 기본 ignore 패턴만 사용합니다.`);
    }
  }

  const extList = Array.from(extensions);
  const globPattern = extList.length > 1 
    ? `**/*.{${extList.map(e => e.replace(/^\./, '')).join(',')}}`
    : `**/*.${extList[0].replace(/^\./, '')}`;

  const files = await glob(globPattern, { cwd: repoPath, ignore: ignorePatterns, absolute: true });
  const allPatterns = [...patterns, ...(options.customPatterns || [])];

  for (const filePath of files) {
    try {
      const ext = path.extname(filePath);
      const stat = fs.statSync(filePath);
      if (stat.size > 2 * 1024 * 1024) continue;

      const isLargeFile = stat.size > 500 * 1024;
      if (isLargeFile) {
        await scanLargeFile(filePath, repoPath, allPatterns, platforms, results, usedEnvNames, options);
      } else {
        await scanSmallFile(filePath, repoPath, allPatterns, platforms, results, usedEnvNames, options);
      }
    } catch (err) {
      logger.warn(`Scan failed for ${filePath}: ${err.message}`);
    }
  }

  const fileWarnings = await scanSensitiveFiles(repoPath, platforms);
  results.push(...fileWarnings);
  return dedupeResults(results, allPatterns);
}

/**
 * dedupeResults
 *
 * The same secret value on the same line can match multiple patterns — the
 * specific one (e.g. "AWS Access Key ID") and the catch-all (e.g. "Generic
 * API Key"). Both findings inflate the report and produce duplicate .env
 * entries. This collapses (file, line, matchValue) groups, keeping the
 * most-specific pattern.
 *
 * Specificity = position in `allPatterns` (lower index = more specific, by
 * convention of patterns.js ordering). Structured-file and sensitive-file
 * findings have no entry in allPatterns; they are always kept (line=0 for
 * sensitive files makes them unlikely to collide anyway).
 */
function dedupeResults(results, allPatterns) {
  const patternRank = new Map();
  allPatterns.forEach((p, i) => patternRank.set(p.name, i));
  const rankOf = r => patternRank.has(r.patternName) ? patternRank.get(r.patternName) : Infinity;

  const candidates = [];
  const standalone = [];

  for (const r of results) {
    if (r.isSensitiveFile || !patternRank.has(r.patternName)) {
      standalone.push(r);
    } else {
      candidates.push(r);
    }
  }

  // Group by (file, line) — overlapping matches always sit on the same line.
  const byLine = new Map();
  for (const r of candidates) {
    const key = `${r.file}|${r.line}`;
    if (!byLine.has(key)) byLine.set(key, []);
    byLine.get(key).push(r);
  }

  const kept = [];
  for (const group of byLine.values()) {
    // Sort by specificity (most-specific first); ties broken by longer match
    // length so substring losers come after the superset winner.
    group.sort((a, b) => {
      const ra = rankOf(a), rb = rankOf(b);
      if (ra !== rb) return ra - rb;
      return b.match.length - a.match.length;
    });

    const accepted = [];
    for (const r of group) {
      const subsumed = accepted.some(a =>
        a.match === r.match || a.match.includes(r.match) || r.match.includes(a.match)
      );
      if (!subsumed) accepted.push(r);
    }
    kept.push(...accepted);
  }

  return reindexEnvVarNames([...standalone, ...kept]);
}

/**
 * reindexEnvVarNames
 *
 * After dedup, envVarNames may contain non-sequential indexes (e.g.
 * `ENDPOINT_URL_321`) because the scanner's per-pattern counter advanced
 * for matches that were later subsumed or filtered. Re-walk the kept
 * results in stable order and reassign indexes per (baseName, value) so
 * users see `_1, _2, _3, ...` instead of `_5, _28, _321`.
 *
 * Same value across multiple findings keeps the same index — only
 * distinct values consume new indexes.
 */
function reindexEnvVarNames(results) {
  const baseCounters = new Map(); // baseName → next index
  const valueIndex = new Map();   // baseName|value → assigned name
  const stripIndex = (name) => name.replace(/_\d+$/, '');

  for (const r of results) {
    if (r.isSensitiveFile || !r.envVarName) continue;
    const base = stripIndex(r.envVarName);
    const key = `${base}|${r.match}`;
    if (valueIndex.has(key)) {
      r.envVarName = valueIndex.get(key);
      continue;
    }
    const next = baseCounters.get(base) || 0;
    const newName = next === 0 ? base : `${base}_${next}`;
    valueIndex.set(key, newName);
    baseCounters.set(base, next + 1);
    r.envVarName = newName;
  }
  return results;
}

