import fs from 'fs';
import path from 'path';
import fg from 'fast-glob';
const { glob } = fg;
import pLimit from 'p-limit';
import logger from '../utils/logger.js';
import ASTProvider from '../ast/ASTProvider.js';
import readline from 'readline';
import { patterns } from './patterns.js';
import type { ScanResult, CodeSecretMatch, SensitiveFileWarning, SecretPattern, Severity } from '../types/index.js';
import type { Platform, ScannerOptions } from '../platforms/types.js';
// 661 LOC 모놀리스에서 분리된 헬퍼/구조화 스캐너 모듈
import {
  isFalsePositive,
  isTestKey,
  isCommentLine,
  collectXmlCommentRanges,
  isLowConfidenceMatch,
  extractMatchDetails,
  getEnvVarName,
  buildLineIndex,
  lineNumberAt
} from './scannerHelpers.js';
import { scanStructuredFile } from './structuredScanner.js';
import { dedupeResults } from './dedupe.js';
import { DEFAULT_IGNORE_PATTERNS } from './defaultIgnores.js';
import { t } from '../utils/i18n.js';

/**
 * Scans for sensitive files that should never be committed.
 */
async function scanSensitiveFiles(repoPath: string, platforms: Platform[]): Promise<SensitiveFileWarning[]> {
  const warnings: SensitiveFileWarning[] = [];
  const sensitiveFiles = platforms.flatMap(p => p.sensitiveFiles || []);

  for (const sf of sensitiveFiles) {
    const found = await glob(sf.glob, {
      cwd: repoPath,
      ignore: ['**/node_modules/**', '**/Pods/**', '**/.git/**'],
      absolute: true
    });

    for (const filePath of found) {
      warnings.push({
        file: path.relative(repoPath, filePath),
        line: 0,
        match: path.basename(filePath),
        fullMatch: path.basename(filePath),
        patternName: t('scanner_sensitive_file_pattern', { file: path.basename(filePath) }),
        severity: sf.severity,
        isTestKey: false,
        isSensitiveFile: true as const,
        isComment: false as const,
        isFixable: false as const,
        content: sf.reason,
        isLikelyExample: false
      });
    }
  }

  return warnings;
}

// Minified/generated one-liners: unbounded-quantifier patterns go quadratic
// on lines this long, pegging the event loop (and the whole pLimit pool).
const MAX_SINGLE_LINE_CHARS = 100000;

async function scanSmallFile(
  filePath: string,
  repoPath: string,
  allPatterns: SecretPattern[],
  platforms: Platform[],
  results: ScanResult[],
  usedEnvNames: Map<string, string>,
  options: ScannerOptions
): Promise<void> {
  let content: string;
  try {
    content = await fs.promises.readFile(filePath, 'utf8');
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    logger.warn(t('scanner_read_err', { file: filePath, msg: message }));
    return;
  }
  const lines = content.split('\n');
  const ext = path.extname(filePath);
  const astLang = ASTProvider.getLangId(ext);

  // A giant minified line ANYWHERE (not just single-line files) triggers the
  // quadratic regex blowup — delegate to the line-based scanner, which skips
  // oversized lines individually instead of losing the whole file.
  if (lines.some(l => l.length > MAX_SINGLE_LINE_CHARS)) {
    return scanLargeFile(filePath, repoPath, allPatterns, platforms, results, usedEnvNames, options);
  }

  const firstTenLines = lines.slice(0, 10).join('\n').toLowerCase();
  if (firstTenLines.includes('auto-generated') || firstTenLines.includes('generated by')) return;

  // XML/HTML/Maven comment ranges span multiple lines; line-based comment
  // detection misses them. Pre-compute byte ranges for `<!-- -->` blocks
  // (XML, HTML, pom.xml, .yml) so URL/secret matches inside reference docs
  // can be skipped (#4.7).
  const xmlCommentRanges = (ext === '.xml' || ext === '.html' || ext === '.htm' || ext === '.svg' || ext === '.yml' || ext === '.yaml')
    ? collectXmlCommentRanges(content)
    : [];
  const inXmlComment = (offset: number): boolean => xmlCommentRanges.some(([s, e]) => offset >= s && offset < e);

  const ctx: MatchContext = { filePath, repoPath, ext, astLang, platforms, options, usedEnvNames, results, inXmlComment };

  // Line number per raw match: an O(file) substring scan per match goes
  // O(matches × file size) on match-heavy files — index line starts once,
  // then binary-search each offset.
  const lineStarts = buildLineIndex(content);

  for (const pattern of allPatterns) {
    // .matchAll() 은 lastIndex 공유 없이 fresh iterator 반환 — 동시성 안전
    // (이전: pattern.regex.exec 루프는 모듈 전역 정규식의 lastIndex 를 공유)
    for (const match of content.matchAll(pattern.regex)) {
      const startLine = lineNumberAt(lineStarts, match.index!);
      await processMatch(pattern, match as RegExpExecArray, content, 0, lines[startLine - 1] || '', startLine, ctx);
    }
  }

  scanStructuredFile(filePath, repoPath, content, results as CodeSecretMatch[], usedEnvNames);
}

interface MatchContext {
  filePath: string;
  repoPath: string;
  ext: string;
  astLang: string | undefined;
  platforms: Platform[];
  options: ScannerOptions;
  usedEnvNames: Map<string, string>;
  results: ScanResult[];
  inXmlComment?: (offset: number) => boolean;
}

/**
 * Shared per-match pipeline for both small- and large-file paths:
 * AST validate → filter (XML comment / low-confidence / comment / postFilter)
 * → push. `sourceText` is whatever match.index is relative to (whole file
 * for the small path, a single line for the large path); `astBaseOffset`
 * converts that to a whole-file string index for the AST engine.
 */
async function processMatch(
  pattern: SecretPattern,
  match: RegExpExecArray,
  sourceText: string,
  astBaseOffset: number,
  lineText: string,
  lineNumber: number,
  ctx: MatchContext
): Promise<void> {
  const { filePath, repoPath, ext, astLang, platforms, options, usedEnvNames, results, inXmlComment } = ctx;
  const { matchValue, varName } = extractMatchDetails(pattern, match, sourceText, ext);

  if (astLang && !options.skipAST) {
    // Use offset of the captured value (not match[0]) so AST validation hits the string literal,
    // not surrounding identifiers (e.g., `apiKey` in `apiKey = "..."`).
    const valueOffsetInMatch = match[0].indexOf(matchValue);
    const valueOffset = astBaseOffset + match.index! + (valueOffsetInMatch >= 0 ? valueOffsetInMatch : 0);
    const isValid = await ASTProvider.validateMatch(filePath, astLang, matchValue, valueOffset, { allowComments: options.scanComments === true });
    if (!isValid) return;
  }

  // Whole-file offset (astBaseOffset converts a line-relative index): keeps
  // the XML-comment test correct in both paths, so populating inXmlComment on
  // the large path can never silently mismatch offsets.
  if (inXmlComment?.(astBaseOffset + match.index!)) return;

  const isComment = isCommentLine(lineText, platforms);
  if (isLowConfidenceMatch(matchValue, pattern.name, varName)) return;
  if (isComment && !options.scanComments) return;
  // Pass matchValue (extracted secret) to postFilter, not full match text
  if (pattern.postFilter && !pattern.postFilter(matchValue)) return;

  const envVarName = getEnvVarName(pattern, varName, match[2], usedEnvNames, matchValue);
  const isTest = isTestKey(lineText, filePath, matchValue);

  results.push({
    file: path.relative(repoPath, filePath),
    line: lineNumber,
    match: matchValue,
    fullMatch: match[0],
    patternName: pattern.name,
    envVarName,
    severity: isTest ? 'LOW' as Severity : pattern.severity,
    isFixable: pattern.isFixable !== false,
    isTestKey: isTest,
    isSensitiveFile: false as const,
    isComment,
    isMultiline: pattern.multiline || match[0].includes('\n'),
    content: lineText.trim(),
    isLikelyExample: isFalsePositive(lineText, filePath)
  } as CodeSecretMatch);
}

async function scanLargeFile(
  filePath: string,
  repoPath: string,
  allPatterns: SecretPattern[],
  platforms: Platform[],
  results: ScanResult[],
  usedEnvNames: Map<string, string>,
  options: ScannerOptions
): Promise<void> {
  const multilinePatterns = allPatterns.filter(p => p.multiline);
  if (multilinePatterns.length > 0) {
    logger.warn(`[Large File] ${path.basename(filePath)}: multiline patterns skipped (${multilinePatterns.map(p => p.name).join(', ')})`);
  }

  let fileStream: fs.ReadStream;
  try {
    fileStream = fs.createReadStream(filePath);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    logger.warn(t('scanner_stream_err', { file: filePath, msg: message }));
    return;
  }
  const rl = readline.createInterface({ input: fileStream, crlfDelay: Infinity });
  const ext = path.extname(filePath);
  const astLang = ASTProvider.getLangId(ext);

  // Detect line ending style for accurate offset calculation
  const headBuf = Buffer.alloc(4096);
  const fd = fs.openSync(filePath, 'r');
  const bytesRead = fs.readSync(fd, headBuf, 0, 4096, 0);
  fs.closeSync(fd);
  // Look for an actual \r\n sequence — a lone CR byte inside a string literal
  // must not flip the whole file to CRLF accounting. Mixed-EOL files still
  // drift (single eolChars for the whole file), accepted residual risk.
  const eolChars = headBuf.subarray(0, bytesRead).includes(Buffer.from('\r\n')) ? 2 : 1; // CRLF=2, LF=1

  let lineNumber = 0;
  // UTF-16 code-unit offset (plain JS string index): ASTProvider reads the
  // file as a string and web-tree-sitter's descendantForIndex expects string
  // indices, NOT UTF-8 byte offsets — byte accounting drifts on any
  // non-ASCII character and silently drops real secrets.
  let charOffset = 0;

  const ctx: MatchContext = { filePath, repoPath, ext, astLang, platforms, options, usedEnvNames, results };

  for await (const line of rl) {
    lineNumber++;
    // Same guard as scanSmallFile's single-line bail, per line: a 500KB+
    // minified bundle read as one giant "line" must not hit the patterns.
    if ((line as string).length > MAX_SINGLE_LINE_CHARS) {
      charOffset += (line as string).length + eolChars;
      continue;
    }
    for (const pattern of allPatterns) {
      if (pattern.multiline) continue;

      // matchAll 사용 — lastIndex 공유 회피
      for (const match of (line as string).matchAll(pattern.regex)) {
        await processMatch(pattern, match as RegExpExecArray, line as string, charOffset, line as string, lineNumber, ctx);
      }
    }
    // +1 for LF. CRLF is handled by crlfDelay: Infinity which strips \r from lines,
    // but the offset still needs to account for \r\n in the file.
    charOffset += (line as string).length + eolChars;
  }
}

/**
 * .blinderSettings 파일을 부모 디렉토리를 탐색하며 찾음
 */
function findBlinderSettings(startPath: string): string | null {
  let current = startPath;
  while (true) {
    const candidate = path.join(current, '.blinderSettings');
    if (fs.existsSync(candidate)) return candidate;
    const parent = path.dirname(current);
    if (parent === current) return null; // 루트 도달
    current = parent;
  }
}

// 프로젝트 루트의 .gitignore를 파싱하여 fast-glob 패턴으로 변환.
// - /secret → secret            (루트 상대 경로)
// - secrets/ → glob(secrets/**)  (디렉토리 전체)
// - secret.key → glob(secret.key)(파일명 전체)
// negation(!), 공줄, 주석은 무시.
function loadGitignorePatterns(repoPath: string): string[] {
  const gitignorePath = path.join(repoPath, '.gitignore');
  if (!fs.existsSync(gitignorePath)) return [];
  try {
    return fs.readFileSync(gitignorePath, 'utf8')
      .split('\n')
      .map(line => line.trim())
      .filter(line => line && !line.startsWith('#') && !line.startsWith('!'))
      .map(p => {
        if (p.startsWith('/')) p = p.slice(1);
        if (p.endsWith('/')) return `**/${p}**`;
        if (!p.includes('/')) return `**/${p}`;
        return p;
      });
  } catch {
    return [];
  }
}

export async function scanProject(repoPath: string, platforms: Platform[], options: ScannerOptions = {}): Promise<ScanResult[]> {
  const results: ScanResult[] = [];
  const extensions = new Set<string>();
  const usedEnvNames = new Map<string, string>();

  platforms.forEach(p => {
    if (!p) return;
    (p.commonExtensions || []).forEach(ext => extensions.add(ext));
  });

  if (extensions.size === 0) {
    ['.swift', '.kt', '.dart', '.xml', '.plist', '.json', '.env', '.properties', '.gradle'].forEach(ext => extensions.add(ext));
  }

  const platformIgnores = platforms.flatMap(p => p.ignorePaths || []);
  const ignorePatterns: string[] = [
    ...DEFAULT_IGNORE_PATTERNS,
    ...platformIgnores, ...(options.ignore || [])
  ];

  // .gitignore 패턴 자동 적용
  const gitignorePatterns = loadGitignorePatterns(repoPath);
  if (gitignorePatterns.length > 0) ignorePatterns.push(...gitignorePatterns);


  // .blinderSettings 추가 ignorePaths 병합
  // - silent catch 제거: 잘못된 JSON 사용자 알림 위해 logger.warn 출력
  // - 스키마 검증(타입/배열) 추가: 잘못된 설정으로 downstream 크래시 방지
  // 참고: bin/blinder.js 호출 경로는 이미 utils/config.js loadConfig 가
  // 동일 파일을 검증해 options.ignore 로 전달하므로 여기 호출은 안전망 역할.
  const rcPath = findBlinderSettings(repoPath);
  if (rcPath && fs.existsSync(rcPath)) {
    try {
      const raw = fs.readFileSync(rcPath, 'utf8');
      const rcContent = JSON.parse(raw) as unknown;
      if (!rcContent || typeof rcContent !== 'object' || Array.isArray(rcContent)) {
        throw new Error('루트는 JSON 객체여야 합니다');
      }
      const rc = rcContent as Record<string, unknown>;
      if (rc.ignorePaths !== undefined) {
        if (!Array.isArray(rc.ignorePaths)) {
          throw new Error('"ignorePaths" 는 배열이어야 합니다');
        }
        ignorePatterns.push(...(rc.ignorePaths as string[]));
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      logger.warn(t('scanner_settings_parse_err', { msg: message }));
    }
  }

  const extList = Array.from(extensions);
  const globPattern = extList.length > 1 
    ? `**/*.{${extList.map(e => e.replace(/^\./, '')).join(',')}}`
    : `**/*.${extList[0].replace(/^\./, '')}`;

  const files = await glob(globPattern, { cwd: repoPath, ignore: ignorePatterns, absolute: true });
  const allPatterns: SecretPattern[] = [...patterns, ...(options.customPatterns || [])];

  const limit = pLimit(16); // WASM OOM 방지: 최대 16개 동시 처리
  const tasks = files.map(filePath => limit(async () => {
    try {
      const stat = await fs.promises.stat(filePath);
      if (stat.size > 2 * 1024 * 1024) return;

      const isLargeFile = stat.size > 500 * 1024;
      if (isLargeFile) {
        await scanLargeFile(filePath, repoPath, allPatterns, platforms, results, usedEnvNames, options);
      } else {
        await scanSmallFile(filePath, repoPath, allPatterns, platforms, results, usedEnvNames, options);
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      logger.warn(t('scanner_scan_failed', { file: filePath, msg: message }));
    }
  }));
  await Promise.all(tasks);

  const fileWarnings = await scanSensitiveFiles(repoPath, platforms);
  results.push(...fileWarnings);
  return dedupeResults(results, allPatterns);
}
